### PR TITLE
Update structure

### PR DESCRIPTION
**Pull request by maxharlow**
A first step in updating the look of the Open Platform site (or: a second attempt at achieving something like https://github.com/guardian/open-platform-site/pull/20)

I'm trying to make it clear that the Content API is a constituent service of the Open Platform, a wider initiative. I think at the moment the two things come across as somewhat muddled. Of course, it's a slightly unclear message as right now the only service in the Open Platform is the Content API. I'm hoping that won't be the case forever though... (Would be great for the Discussion API to be there too, for example.)

This:
- moves the Content API site to `/content-api`, making the information architecture clearer
- updates the Content API pages to use the Content API header
- creates an updated index page with a separate Open Platform identity (and it should also work on mobile)

The next step would be to make the Content API site look more like a sub-site of the Open Platform, but I didn't want to do too much at once.

Screenshots:

screen shot 2014-12-31 at 12 23 39

screen shot 2014-12-31 at 12 23 18

:goat: :gift:

### CODE REVIEW

**Comment by philmcmahon** [comment]
Looks good. When I open open-platform-site/index.html the footer is in a kind of grey colour whilst the "The open platform is a..." box is in white. Maybe it would look better if these were the same colour?

**Comment by maxharlow** [comment]
I've tried to take the colours/style from NGW (but using the purple from our Twitter account)... that's where that dark grey comes from

**Comment by philmcmahon** [comment]
:+1:

**Comment by mchv** [comment]
:+1:

**Comment by chriswilk** [comment]
@maxharlow Sorry to put a spanner in the works here - I have asked for this to be reverted.  Grab me later for the detail.

**Pull request merged**
